### ISSUE TITLE
Academic timetable view option

### ISSUE THREAD

**Issue by VenkataDheeraj** [amrita-repository/android-app#65]
**Describe the bug**
-> I'm unable to view the academic timetable though I can download it in my device.

**To Reproduce**
1. Go to 'Academic Timetable'
2. Set the options for 7th semester EIE B.Tech for 2020-21
3. Click on 'View'
4. It says the timetable hasn't been uploaded

**Expected behavior**
-> It should the timetable for the given inputs.

**Screenshots**

**Desktop (please complete the following information):**
 - OS:
 - Android Studio Version

**Smartphone (please complete the following information):**
 - Device: Huawei Honor 7x
 - OS: Android 9(EMUI 9.1)

**Additional context**

**Comment by jodtribhu** [comment]
I think its because the file was not uploaded onto the site in the intranet since it is the 2020 -21 batch  .When I checked the link which is used to get the timetable from intranet from the code  it says 'Sorry....Time table not yet uploaded.   Check back later' and this is seen as toast message in the app

**Comment by rajkumaar23** [comment]
No, the file is displayed for a short span of time and then exits throwing that toast. It's a bug.

**Comment by jodtribhu** [comment]
Can I see the stacktrace of the error from the logcat

**Comment by rajkumaar23** [comment]
@VenkataDheeraj Can you update the app and verify if the bug you raised has been fixed ?
